apiVersion: app/v1
kind: Deployment
metadata:
  name: fastapi-deployment
specs:
  replicas: 1
  selector:
    matchLables:
      app: fastapi
  template:
    metadata:
      lables:
        app: fastapi
    spec:
      container:
        - name: fastapi
          image: jaanuk/fastapi-app:1.3
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
specs:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80